server:
  port: 9000
  tomcat:
    threads:
      min-spare: 20
      max: 100

spring:
  profiles:
    active: redis-standalone

---
spring:
  config:
    activate:
      on-profile: redis-standalone

  data:
    redis:
      mode: standalone
      nodes:
        server-1: localhost:6379,
        server-2: localhost:6380,
        server-3: localhost:6381,
      command-timeout: 1000 # 1000ms
      shutdown-timeout: 100 # 100ms

logging:
  level:
    io.lettuce.core: debug

---
spring:
  config:
    activate:
      on-profile: redis-cluster

  data:
    redis:
      mode: cluster
      nodes:
        server-1:
          localhost:16379,
          localhost:26379,
          localhost:36379,
      command-timeout: 60000 # 60s
      shutdown-timeout: 100 # 100ms

logging:
  level:
    io.lettuce.core: debug
